import type { Product } from './store'

export const categories = [
  { id: 'food', name: 'Food & Groceries', nameAr: 'المواد الغذائية' },
  { id: 'beverages', name: 'Beverages', nameAr: 'المشروبات' },
  { id: 'cleaning', name: 'Cleaning Supplies', nameAr: 'مواد التنظيف' },
  { id: 'personal', name: 'Personal Care', nameAr: 'العناية الشخصية' },
  { id: 'electronics', name: 'Electronics', nameAr: 'الإلكترونيات' },
  { id: 'home', name: 'Home & Kitchen', nameAr: 'المنزل والمطبخ' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Rice 25kg',
    nameAr: 'أرز بسمتي فاخر ٢٥ كيلو',
    description: 'High-quality basmati rice, perfect for wholesale',
    descriptionAr: 'أرز بسمتي عالي الجودة، مثالي للبيع بالجملة',
    wholesalePrice: 45000,
    retailPrice: 52000,
    minQuantity: 10,
    category: 'food',
    categoryAr: 'المواد الغذائية',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    stock: 500,
    unit: 'bag',
    unitAr: 'كيس',
  },
  {
    id: '2',
    name: 'Vegetable Oil 5L',
    nameAr: 'زيت نباتي ٥ لتر',
    description: 'Pure vegetable cooking oil',
    descriptionAr: 'زيت طبخ نباتي نقي',
    wholesalePrice: 12000,
    retailPrice: 14500,
    minQuantity: 24,
    category: 'food',
    categoryAr: 'المواد الغذائية',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
    stock: 300,
    unit: 'bottle',
    unitAr: 'زجاجة',
  },
  {
    id: '3',
    name: 'Sugar 50kg',
    nameAr: 'سكر أبيض ٥٠ كيلو',
    description: 'Premium white sugar',
    descriptionAr: 'سكر أبيض فاخر',
    wholesalePrice: 35000,
    retailPrice: 42000,
    minQuantity: 20,
    category: 'food',
    categoryAr: 'المواد الغذائية',
    image: 'https://images.unsplash.com/photo-1550411294-098958786a7d?w=400&h=400&fit=crop',
    stock: 400,
    unit: 'bag',
    unitAr: 'كيس',
  },
  {
    id: '4',
    name: 'Instant Coffee 200g',
    nameAr: 'قهوة سريعة التحضير ٢٠٠ جرام',
    description: 'Premium instant coffee',
    descriptionAr: 'قهوة سريعة التحضير فاخرة',
    wholesalePrice: 8500,
    retailPrice: 10000,
    minQuantity: 48,
    category: 'beverages',
    categoryAr: 'المشروبات',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
    stock: 200,
    unit: 'jar',
    unitAr: 'برطمان',
  },
  {
    id: '5',
    name: 'Black Tea 500g',
    nameAr: 'شاي أسود ٥٠٠ جرام',
    description: 'Premium Ceylon black tea',
    descriptionAr: 'شاي سيلاني أسود فاخر',
    wholesalePrice: 6000,
    retailPrice: 7500,
    minQuantity: 50,
    category: 'beverages',
    categoryAr: 'المشروبات',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=400&fit=crop',
    stock: 350,
    unit: 'pack',
    unitAr: 'عبوة',
  },
  {
    id: '6',
    name: 'Detergent Powder 5kg',
    nameAr: 'مسحوق غسيل ٥ كيلو',
    description: 'Heavy-duty laundry detergent',
    descriptionAr: 'مسحوق غسيل قوي للملابس',
    wholesalePrice: 15000,
    retailPrice: 18000,
    minQuantity: 30,
    category: 'cleaning',
    categoryAr: 'مواد التنظيف',
    image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400&h=400&fit=crop',
    stock: 250,
    unit: 'bag',
    unitAr: 'كيس',
  },
  {
    id: '7',
    name: 'Dish Soap 1L',
    nameAr: 'صابون أطباق ١ لتر',
    description: 'Concentrated dish washing liquid',
    descriptionAr: 'سائل غسيل أطباق مركز',
    wholesalePrice: 3500,
    retailPrice: 4500,
    minQuantity: 48,
    category: 'cleaning',
    categoryAr: 'مواد التنظيف',
    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400&h=400&fit=crop',
    stock: 400,
    unit: 'bottle',
    unitAr: 'زجاجة',
  },
  {
    id: '8',
    name: 'Shampoo 400ml',
    nameAr: 'شامبو ٤٠٠ مل',
    description: 'Anti-dandruff shampoo',
    descriptionAr: 'شامبو مضاد للقشرة',
    wholesalePrice: 5500,
    retailPrice: 7000,
    minQuantity: 36,
    category: 'personal',
    categoryAr: 'العناية الشخصية',
    image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400&h=400&fit=crop',
    stock: 180,
    unit: 'bottle',
    unitAr: 'زجاجة',
  },
  {
    id: '9',
    name: 'Toothpaste 150g',
    nameAr: 'معجون أسنان ١٥٠ جرام',
    description: 'Whitening toothpaste with fluoride',
    descriptionAr: 'معجون أسنان مبيض بالفلورايد',
    wholesalePrice: 2500,
    retailPrice: 3200,
    minQuantity: 72,
    category: 'personal',
    categoryAr: 'العناية الشخصية',
    image: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=400&h=400&fit=crop',
    stock: 500,
    unit: 'tube',
    unitAr: 'أنبوب',
  },
  {
    id: '10',
    name: 'LED Bulb 12W',
    nameAr: 'لمبة ليد ١٢ واط',
    description: 'Energy-saving LED bulb',
    descriptionAr: 'لمبة ليد موفرة للطاقة',
    wholesalePrice: 4000,
    retailPrice: 5500,
    minQuantity: 50,
    category: 'electronics',
    categoryAr: 'الإلكترونيات',
    image: 'https://images.unsplash.com/photo-1532007799299-d0a68a9dc91a?w=400&h=400&fit=crop',
    stock: 600,
    unit: 'piece',
    unitAr: 'قطعة',
  },
  {
    id: '11',
    name: 'Power Strip 5 Outlets',
    nameAr: 'مشترك كهربائي ٥ مخارج',
    description: 'Surge-protected power strip',
    descriptionAr: 'مشترك كهربائي مع حماية من الصواعق',
    wholesalePrice: 8000,
    retailPrice: 10500,
    minQuantity: 24,
    category: 'electronics',
    categoryAr: 'الإلكترونيات',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    stock: 150,
    unit: 'piece',
    unitAr: 'قطعة',
  },
  {
    id: '12',
    name: 'Stainless Steel Pot Set',
    nameAr: 'طقم قدور ستانلس ستيل',
    description: '5-piece stainless steel pot set',
    descriptionAr: 'طقم قدور ستانلس ستيل ٥ قطع',
    wholesalePrice: 65000,
    retailPrice: 80000,
    minQuantity: 10,
    category: 'home',
    categoryAr: 'المنزل والمطبخ',
    image: 'https://images.unsplash.com/photo-1584990347449-a6efbc9f7a5b?w=400&h=400&fit=crop',
    stock: 80,
    unit: 'set',
    unitAr: 'طقم',
  },
]

export const heroSlides = [
  {
    id: 1,
    title: 'أفضل أسعار الجملة',
    subtitle: 'وفر أكثر مع كميات أكبر',
    description: 'تسوق من أكبر تشكيلة منتجات بأسعار الجملة',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=1200&h=600&fit=crop',
    cta: 'تسوق الآن',
  },
  {
    id: 2,
    title: 'عروض خاصة',
    subtitle: 'خصومات تصل إلى ٣٠٪',
    description: 'استفد من عروضنا الحصرية على المنتجات المختارة',
    image: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200&h=600&fit=crop',
    cta: 'اكتشف العروض',
  },
  {
    id: 3,
    title: 'توصيل سريع',
    subtitle: 'لجميع محافظات اليمن',
    description: 'نوصل طلباتك إلى باب منزلك في أسرع وقت',
    image: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?w=1200&h=600&fit=crop',
    cta: 'اطلب الآن',
  },
]

export const dealOfTheDay = {
  product: products[0],
  discount: 15,
  endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
}

export const discountCodes: Record<string, number> = {
  'JOMLAH10': 10,
  'WELCOME15': 15,
  'BULK20': 20,
}
